# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/SSWPersonalData/Project/Vivado/ASKModulate/ASKModulate.srcs/sources_1/ip/xfft_analyze/xfft_analyze.xci
# IP: The module: 'xfft_analyze' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/SSWPersonalData/Project/Vivado/ASKModulate/ASKModulate.gen/sources_1/ip/xfft_analyze/xfft_analyze_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xfft_analyze'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/SSWPersonalData/Project/Vivado/ASKModulate/ASKModulate.srcs/sources_1/ip/xfft_analyze/xfft_analyze.xci
# IP: The module: 'xfft_analyze' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/SSWPersonalData/Project/Vivado/ASKModulate/ASKModulate.gen/sources_1/ip/xfft_analyze/xfft_analyze_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xfft_analyze'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
