######################################################################
#
# File name : TB_TOP_wave.do
# Created on: Thu Nov 17 14:12:55 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
