######################################################################
#
# File name : TB_TOP_compile.do
# Created on: Thu Nov 17 14:26:18 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/work
D:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim

D:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_2020.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_2020.4\\win64\\vcom  -93 -work xil_defaultlib  \
"../../../../ASKModulate.gen/sources_1/ip/xfft_analyze/sim/xfft_analyze.vhd" \
"../../../../ASKModulate.gen/sources_1/ip/mult_gen_0/sim/mult_gen_0.vhd" \

D:\\modeltech64_2020.4\\win64\\vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../ASKModulate.srcs/sources_1/new/1Bto2B.v" \
"../../../../ASKModulate.srcs/sources_1/new/ASKMOD.v" \
"../../../../ASKModulate.srcs/sources_1/new/DDS.v" \
"../../../../ASKModulate.srcs/sources_1/new/Freq_Divider.v" \
"../../../../ASKModulate.srcs/sources_1/new/RCosFIR.v" \
"../../../../ASKModulate.srcs/sources_1/new/Scramber.v" \
"../../../../ASKModulate.srcs/sources_1/new/TOP.v" \
"../../../../ASKModulate.srcs/sources_1/new/myFFT.v" \
"../../../../ASKModulate.srcs/sim_1/new/TB_TOP.v" \

# compile glbl module
D:\\modeltech64_2020.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

